### PR TITLE
MAG2-122 - Fixed Mage2-Core bug with wrong order status

### LINKED ISSUE #253: Orders with virtual products get wrong status "Closed"
Orders in our magento 2.3.2 shop with virtual products like downloads get the status "Closed" instead of "Complete" after the transaction status "paid" is submitted from Payone. After reading the magento docs I think this is the wrong status. Also the button for credit memo (Gutschrift) is missing in admin in these orders and corresponding invoices. This seems to be even the main reason for this: I hunted down the code responsible for this in vendor/magento/module-sales/Model/ResourceModel/Order/Handler/State.php:

if (in_array($currentState, [Order::STATE_PROCESSING, Order::STATE_COMPLETE])
		&& !$order->canCreditmemo()
		&& !$order->canShip()
) {
		$order->setState(Order::STATE_CLOSED)
				->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_CLOSED));

So why would these orders have canCreditmemo() == false? Orders which get shipped are not affected by this. Also orders which use Paypal Express get the correct status "Complete".

### PR DESCRIPTION
**Pull request by FatchipRobert**
Fixes #253

### CODE REVIEW

**Comment by webpeaks63** [comment]
After checking this fix, it appeared that it doesn't work as expected.

The virtual order should be in state "complete" after payment went through.
With your current code it would remain at "processing".

Line 78 of Model/Plugins/State.php is:

} elseif ($currentState === Order::STATE_PROCESSING && !$order->canShip() && **!$order->getIsVirtual()) { // added !$order->getIsVirtual()**

but should be:

} elseif ($currentState === Order::STATE_PROCESSING && !$order->canShip() && **$order->getIsVirtual()**) { // added $order->getIsVirtual()
$order->setState(Order::STATE_COMPLETE)->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_COMPLETE));

Regards
Thomas

**Comment by alexandergolz** [comment]
> After checking this fix, it appeared that it doesn't work as expected.
> 
> The virtual order should be in state "complete" after payment went through.
> With your current code it would remain at "processing".
> 
> Line 78 of Model/Plugins/State.php is:
> 
> } elseif ($currentState === Order::STATE_PROCESSING && !$order->canShip() && **!$order->getIsVirtual()) { // added !$order->getIsVirtual()**
> 
> but should be:
> 
> } elseif ($currentState === Order::STATE_PROCESSING && !$order->canShip() && **$order->getIsVirtual()**) { // added $order->getIsVirtual()
> $order->setState(Order::STATE_COMPLETE)->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_COMPLETE));
> 
> Regards
> Thomas

I'm on Magento 2.3.3 and orders with only downloadable Products now get status "Processing" instead of "Closed" (which they did before this commit). But it should be "Complete". Your comment addresses this issue but was not included in the commt, am I right?

Regards

Alexander

**Comment by webpeaks63** [comment]
Your right, they didn't included it...

**Comment by FatchipRobert** [comment]
We checked your changes thoroughly, but they would have caused the Status Mapping of the Payone module to behave differently for physical orders and downloadable orders, which would be very confusing.

You should instead configure the Status Mapping for the used payment methods for example to the following:
APPOINTED => Processing
PAID => Complete

**Comment by webpeaks63** [comment]
??? The status for physical order should only show "complete" after shipment, not after payment. For downloadable orders the order status should be complete after payment. This is not confusing, it is the way it should go.

**Pull request merged**
