### PR TITLE
MAG2-142 - See #293 Adds reference number prefix length comment

### LINKED ISSUE #293: Long ReferenceNumber Prefix results in 1003: Reference Number faulty or missing
If the referencenumber prefix (admin > stores > config > payone > general > global > referencenumber prefix) exceeds (a not yet defined number of) characters, the checkout process returns an error `1003: An error occurred while processing this transaction (wrong parameters)`

Test: set referencenumber prefix to "abcdefghijklmnopqrstuvwxyz" and try to checkout.

Possible fix: define and document the allowed number of characters for this field. validate the entered string to not exceed the defined character limit

@fjbender if you figure the number I might be able to create a PR :-)

### PR DESCRIPTION
**Pull request by riconeitzel**
Fixes #293 (ish)

### CODE REVIEW

**Comment by fjbender** [comment]
Thanks! Moved this to QA

**Comment by fjbender** [comment]
Somehow, this text doesn't show up (it didn't even show up before when it only said "optional"), any idea?

**Comment by riconeitzel** [comment]
@fjbender aaaaand it's (not) gone :-) \o/

**Comment by fjbender** [comment]
Thanks again for your contribution! :)

**Pull request merged**
